// Henry's to-do seed data — implements the PRD "To-Do Agent Data Model & Occurrence Engine".
// All goals scoped to EOY 2026. Every task uses missPolicy 'carry': a missed occurrence
// stays pending until it is explicitly marked done or skipped (missed).
// Applied once by the v1 → v2 migration in store.ts; the user's time zone lives in config.ts.
import type { Goal, Task } from './types';

const NOW = '2026-10-03T12:00:00-04:00';

export const goals: Goal[] = [
  {
    id: 'goal-weight-162-5',
    pillar: 'health',
    title: 'Reach 162.5 lb bodyweight',
    status: 'active',
    targetDate: '2026-12-31',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'goal-interview-ready',
    pillar: 'wealth',
    title: 'Interview-ready for S-tier companies',
    status: 'active',
    targetDate: '2026-12-31',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'goal-golf-handicap',
    pillar: 'happiness',
    title: 'Golf handicap under 5.0',
    status: 'active',
    targetDate: '2026-12-31',
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const tasks: Task[] = [
  // ── Health → Reach 162.5 lb bodyweight
  {
    id: 'task-weigh-in',
    title: 'Log morning weight',
    goalIds: ['goal-weight-162-5'],
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-lift',
    title: 'Lift',
    goalIds: ['goal-weight-162-5'],
    rrule: 'FREQ=WEEKLY;BYDAY=TU,TH,SA',
    startDate: '2026-10-06',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-water',
    title: 'Log water (3L)',
    goalIds: ['goal-weight-162-5'],
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-log-meals',
    title: 'Log meals and snacks',
    goalIds: ['goal-weight-162-5'],
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-no-alcohol',
    title: 'No alcohol',
    goalIds: ['goal-weight-162-5'],
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-no-fried',
    title: 'No deep-fried food',
    goalIds: ['goal-weight-162-5'],
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-no-dessert',
    title: 'No dessert',
    goalIds: ['goal-weight-162-5'],
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── Wealth → Interview-ready for S-tier companies
  {
    id: 'task-leetcode',
    title: '1 LeetCode medium',
    goalIds: ['goal-interview-ready'],
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-tech-reading',
    title: 'Read 15 pages of a technical book',
    goalIds: ['goal-interview-ready'],
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-agent-app',
    title: 'Work on agent application',
    goalIds: ['goal-interview-ready'],
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── Happiness → Golf handicap under 5.0
  {
    id: 'task-golf-practice',
    title: 'Golf practice',
    goalIds: ['goal-golf-handicap'],
    rrule: 'FREQ=WEEKLY;BYDAY=MO,WE,FR',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-golf-round',
    title: 'Play a round of golf',
    goalIds: ['goal-golf-handicap'],
    rrule: 'FREQ=WEEKLY;INTERVAL=2;BYDAY=SA',
    startDate: '2026-10-10',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── Pillar-only (no specific goal)
  {
    id: 'task-wake-630',
    title: 'Wake up at 6:30 AM',
    goalIds: [],
    pillar: 'health',
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-stretch',
    title: 'Stretch / mobility',
    goalIds: [],
    pillar: 'health',
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-dental',
    title: 'Nightly dental hygiene',
    goalIds: [],
    pillar: 'health',
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-budget',
    title: 'Check budget',
    goalIds: [],
    pillar: 'wealth',
    rrule: 'FREQ=WEEKLY;BYDAY=SU',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-walk-dog',
    title: 'Walk the dog',
    goalIds: [],
    pillar: 'happiness',
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-partner-time',
    title: 'Time with partner',
    goalIds: [],
    pillar: 'happiness',
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'task-screen-time',
    title: 'Screen time under 2 hr',
    goalIds: [],
    pillar: 'happiness',
    rrule: 'FREQ=DAILY',
    startDate: '2026-10-04',
    missPolicy: 'carry',
    active: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];
