import { createSdkMcpServer, tool } from "@anthropic-ai/claude-agent-sdk";
import { z } from "zod";
import { services as defaultServices, type Services } from "@/lib/domain/service";
import { DomainError, GoalStatus, MissPolicy, Pillar } from "@/lib/domain/types";

export const TODO_SERVER = "todos";
/** Tools that change stored data; the UI refreshes the agenda panel after these. */
export const MUTATING_TOOLS = new Set([
  "completeOccurrence",
  "skipOccurrence",
  "reopenOccurrence",
  "createTask",
  "updateTask",
  "archiveTask",
  "createGoal",
  "updateGoal",
]);

const json = (value: unknown) => ({
  content: [{ type: "text" as const, text: JSON.stringify(value) }],
});

const fail = (error: unknown) => ({
  content: [
    {
      type: "text" as const,
      text: JSON.stringify(
        error instanceof DomainError
          ? { code: error.code, message: error.message }
          : { code: "INTERNAL", message: error instanceof Error ? error.message : String(error) },
      ),
    },
  ],
  isError: true,
});

const guarded =
  <A>(fn: (args: A) => Promise<unknown>) =>
  async (args: A) => {
    try {
      return json(await fn(args));
    } catch (error) {
      return fail(error);
    }
  };

const date = (what: string) => z.string().describe(`${what} (YYYY-MM-DD, user's local date)`);
const note = z.string().optional().describe("Optional short note, e.g. a value logged for the day");
const rrule = z
  .string()
  .describe("RFC 5545 rule body without DTSTART, e.g. FREQ=DAILY or FREQ=WEEKLY;BYDAY=MO,WE,FR");

// Thin wrappers over the domain services the web app also uses. Occurrences are only ever
// generated by service code; no tool can insert one.
export function createTodoTools(services: Services = defaultServices) {
  return [
    tool(
      "getAgenda",
      "Occurrences scheduled in [from, to] joined with task title, goals and pillars, plus every overdue pending occurrence from before `from` when `from` is today or earlier. Range ≤ 366 days. Also use for history over past ranges.",
      { from: date("Range start"), to: date("Range end, inclusive") },
      guarded(({ from, to }) => services.getAgenda(from, to)),
    ),
    tool(
      "completeOccurrence",
      "Mark one occurrence done (idempotent). Works for past and skipped occurrences to backfill.",
      { id: z.string().describe("occurrenceId from getAgenda"), note },
      guarded(({ id, note }) => services.completeOccurrence(id, note)),
    ),
    tool(
      "skipOccurrence",
      "Mark one occurrence skipped (missed / not done).",
      { id: z.string().describe("occurrenceId from getAgenda"), note },
      guarded(({ id, note }) => services.skipOccurrence(id, note)),
    ),
    tool(
      "reopenOccurrence",
      "Set one occurrence back to pending, e.g. to undo a mistaken completion.",
      { id: z.string().describe("occurrenceId from getAgenda") },
      guarded(({ id }) => services.reopenOccurrence(id)),
    ),
    tool(
      "createTask",
      "Create a task. With rrule it recurs; without, it is ad hoc and gets one occurrence on dueAt (or startDate). Align it with goalIds, or a pillar if no specific goal fits.",
      {
        title: z.string().min(1),
        rrule: rrule.optional(),
        startDate: date("Rule anchor / creation date; defaults to today").optional(),
        dueAt: date("Due date, ad hoc tasks only").optional(),
        goalIds: z.array(z.string()).optional(),
        pillar: Pillar.optional(),
        missPolicy: MissPolicy.optional().describe(
          "carry (default): missed occurrences stay pending as overdue; skip: they auto-skip",
        ),
      },
      guarded((args) => services.createTask(args)),
    ),
    tool(
      "updateTask",
      "Edit a task; only given fields change, null clears. Changing rrule/startDate/dueAt removes future pending occurrences (history is kept); a new rrule without startDate starts today.",
      {
        id: z.string(),
        title: z.string().min(1).optional(),
        rrule: rrule.nullable().optional().describe("null converts to ad hoc"),
        startDate: date("New rule anchor").optional(),
        dueAt: date("Due date, ad hoc only").nullable().optional(),
        goalIds: z.array(z.string()).optional(),
        pillar: Pillar.nullable().optional(),
        missPolicy: MissPolicy.optional(),
        active: z.boolean().optional(),
      },
      guarded(({ id, ...patch }) => services.updateTask(id, patch)),
    ),
    tool(
      "archiveTask",
      "Archive a task: no new occurrences, future pending ones removed, history kept.",
      { id: z.string() },
      guarded(({ id }) => services.archiveTask(id)),
    ),
    tool(
      "listTasks",
      "List task definitions (ids, rules, goals, pillars). Use to find a task id that isn't on the agenda.",
      { active: z.boolean().optional(), goalId: z.string().optional(), pillar: Pillar.optional() },
      guarded((args) => services.listTasks(args)),
    ),
    tool(
      "listUnalignedTasks",
      "Active tasks with no goal and no pillar.",
      {},
      guarded(() => services.listUnalignedTasks()),
    ),
    tool(
      "createGoal",
      "Create a goal under a pillar. A parent goal must be in the same pillar.",
      {
        pillar: Pillar,
        title: z.string().min(1),
        parentId: z.string().optional(),
        status: GoalStatus.optional(),
        targetDate: date("Target date").optional(),
      },
      guarded((args) => services.createGoal(args)),
    ),
    tool(
      "updateGoal",
      "Edit a goal; only given fields change, null clears. Pausing a goal does not affect its tasks.",
      {
        id: z.string(),
        pillar: Pillar.optional(),
        title: z.string().min(1).optional(),
        parentId: z.string().nullable().optional(),
        status: GoalStatus.optional(),
        targetDate: date("Target date").nullable().optional(),
      },
      guarded(({ id, ...patch }) => services.updateGoal(id, patch)),
    ),
    tool(
      "listGoals",
      "Goals with child goal ids and active linked task counts.",
      { pillar: Pillar.optional(), status: GoalStatus.optional() },
      guarded((args) => services.listGoals(args)),
    ),
    tool(
      "getPillarSummary",
      "done/skipped/pending counts per pillar and per goal over [from, to], plus unaligned counts.",
      { from: date("Range start"), to: date("Range end, inclusive") },
      guarded(({ from, to }) => services.getPillarSummary(from, to)),
    ),
  ];
}

export function createTodoServer() {
  return createSdkMcpServer({ name: TODO_SERVER, version: "2.0.0", tools: createTodoTools() });
}
